#!/usr/bin/env node
// Builds platform token files from design/tokens.json. Zero dependencies.
//   node design/build-tokens.mjs
// Outputs:
//   web/src/styles/tokens.css                                   (CSS custom properties, light/dark)
//   mobile/android/app/src/main/res/values/ds_tokens.xml        (light colors + dimens + integers)
//   mobile/android/app/src/main/res/values-night/ds_tokens.xml  (dark colors)
// Also checks WCAG contrast of every text token against the surfaces it sits on and fails on < 4.5:1.
import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const tokens = JSON.parse(readFileSync(join(root, "design/tokens.json"), "utf8"));

const get = (path) => path.split(".").reduce((node, key) => node?.[key], tokens);
const resolve = (value, seen = []) => {
  if (typeof value !== "string" || !/^\{.+\}$/.test(value)) return value;
  const path = value.slice(1, -1);
  if (seen.includes(path)) throw new Error(`Circular reference: ${[...seen, path].join(" -> ")}`);
  const target = get(path);
  if (!target || !("$value" in target)) throw new Error(`Unresolved reference ${value}`);
  return resolve(target.$value, [...seen, path]);
};

// Walk a subtree; yields [pathSegments, resolvedValue] for every token ($value node).
function* walk(node, path = []) {
  if (node && typeof node === "object" && "$value" in node) {
    yield [path, resolve(node.$value)];
    return;
  }
  for (const [key, child] of Object.entries(node ?? {})) {
    if (!key.startsWith("$") && child && typeof child === "object") yield* walk(child, [...path, key]);
  }
}

const cssName = (path) => `--ds-${path.join("-")}`;
const cssValue = (value) => (Array.isArray(value) ? `cubic-bezier(${value.join(", ")})` : String(value));

// ---------- CSS ----------
const globalLines = [];
for (const group of ["font", "type", "space", "radius", "border", "z", "breakpoint"]) {
  for (const [path, value] of walk(tokens[group])) globalLines.push(`  ${cssName([group, ...path])}: ${cssValue(value)};`);
}
for (const [path, value] of walk(tokens.motion)) {
  if (path[0] === "spring") continue; // springs are consumed from tokens.json by the JS motion layer
  globalLines.push(`  ${cssName(["motion", ...path])}: ${cssValue(value)};`);
}
for (const [path, value] of walk(tokens.icon)) {
  if (path[0] !== "map") globalLines.push(`  ${cssName(["icon", ...path])}: ${cssValue(value)};`);
}

const themeLines = (mode) => [
  ...[...walk(tokens.theme[mode])].map(([path, value]) => `  ${cssName(path)}: ${value};`),
  ...[...walk(tokens.shadow[mode])].map(([path, value]) => `  ${cssName(["shadow", ...path])}: ${value};`),
];

const light = themeLines("light").join("\n");
const dark = themeLines("dark").join("\n");
const css = `/* Generated by design/build-tokens.mjs from design/tokens.json. Do not edit by hand. */
:root {
${globalLines.join("\n")}
}

:root,
:root[data-theme="light"] {
  color-scheme: light;
${light}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${dark.replaceAll(/^/gm, "  ")}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${dark}
}
`;

// ---------- Android ----------
const androidColor = (hex) => {
  const h = hex.toLowerCase();
  if (/^#[0-9a-f]{6}$/.test(h)) return h;
  if (/^#[0-9a-f]{8}$/.test(h)) return `#${h.slice(7, 9)}${h.slice(1, 7)}`; // #RRGGBBAA -> #AARRGGBB
  throw new Error(`Android needs hex colors, got ${hex}`);
};
const resName = (path) => `ds_${path.join("_").replaceAll("-", "_")}`;
const colorXml = (mode) =>
  [...walk(tokens.theme[mode])].map(([path, value]) => `    <color name="${resName(path)}">${androidColor(value)}</color>`).join("\n");

const dimens = [];
for (const [path, value] of walk(tokens.space)) dimens.push(`    <dimen name="${resName(["space", ...path])}">${value.replace("px", "dp")}</dimen>`);
for (const [path, value] of walk(tokens.radius)) dimens.push(`    <dimen name="${resName(["radius", ...path])}">${value.replace("px", "dp")}</dimen>`);
for (const [path, value] of walk(tokens.icon.size)) dimens.push(`    <dimen name="${resName(["icon", ...path])}">${value.replace("px", "dp")}</dimen>`);
for (const [path, value] of walk(tokens.type)) {
  if (path[1] === "size" || path[1] === "line") dimens.push(`    <dimen name="${resName(["text", ...path])}">${value.replace("px", "sp")}</dimen>`);
}
const integers = [...walk(tokens.motion.duration)].map(
  ([path, value]) => `    <integer name="${resName(["motion", ...path])}">${parseInt(value, 10)}</integer>`,
);

const header = "<?xml version=\"1.0\" encoding=\"utf-8\"?>\n<!-- Generated by design/build-tokens.mjs from design/tokens.json. Do not edit by hand. -->\n<resources>\n";
const lightXml = `${header}${colorXml("light")}\n\n${dimens.join("\n")}\n\n${integers.join("\n")}\n    <item name="ds_icon_stroke" format="float" type="dimen">${tokens.icon.stroke.$value}</item>\n</resources>\n`;
const darkXml = `${header}${colorXml("dark")}\n</resources>\n`;

// ---------- Contrast gate (WCAG 2.x) ----------
const lum = (hex) => {
  const [r, g, b] = [1, 3, 5].map((i) => parseInt(hex.slice(i, i + 2), 16) / 255)
    .map((c) => (c <= 0.03928 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4));
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const contrast = (a, b) => {
  const [hi, lo] = [lum(a), lum(b)].sort((x, y) => y - x);
  return (hi + 0.05) / (lo + 0.05);
};
const failures = [];
const rows = [];
for (const mode of ["light", "dark"]) {
  const t = (path) => resolve(get(`theme.${mode}.${path}`).$value);
  const pairs = [
    ...["primary", "secondary", "muted", "link"].flatMap((k) => ["surface", "page", "raised"].map((bg) => [`text.${k}`, `bg.${bg}`, 4.5])),
    ...["ok", "regular", "alert", "offline"].flatMap((s) => [[`state.${s}.text`, `state.${s}.subtle`, 4.5], [`state.${s}.text`, "bg.surface", 4.5]]),
    ["intent.info", "intent.info-subtle", 4.5],
    ["brand.on-ink", "brand.ink", 4.5],
    ["border.focus", "bg.surface", 3],
    ...["temp", "rh", "noise"].map((m) => [`metric.${m}`, "bg.surface", 3]),
  ];
  for (const [fg, bg, min] of pairs) {
    const ratio = contrast(t(fg), t(bg));
    rows.push(`${mode.padEnd(5)} ${fg.padEnd(22)} on ${bg.padEnd(20)} ${ratio.toFixed(2).padStart(5)}:1 ${ratio >= min ? "ok" : `FAIL (< ${min})`}`);
    if (ratio < min) failures.push(rows.at(-1));
  }
}

const write = (relative, content) => {
  const file = join(root, relative);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, content);
  console.log(`wrote ${relative}`);
};
write("web/src/styles/tokens.css", css);
write("mobile/android/app/src/main/res/values/ds_tokens.xml", lightXml);
write("mobile/android/app/src/main/res/values-night/ds_tokens.xml", darkXml);
console.log(`\nContrast check (${rows.length} pairs; lux/presence marks are relieved by always-visible labels):`);
if (process.argv.includes("--verbose")) console.log(rows.join("\n"));
if (failures.length) {
  console.error(failures.join("\n"));
  process.exit(1);
}
console.log("all pairs pass");
